<?
  // Set page title.
  $this->headTitle($this->translate('YO this'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Text this') . '</li>';
?>
<?=$this->flashmessages()?>
<form method="post" action="" name="smsRecord" class="form-horizontal">
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" />
  <div class="form-group">
    <label class="col-sm-3 control-label" for="sms_to"><?=$this->transEsc('Username')?>:</label>
    <div class="col-sm-9">
      <input id="sms_to" type="text" name="username" placeholder="YO USERNAME" class="form-control"/>
    </div>
  </div>
  <?=$this->recaptcha()->html($this->useRecaptcha) ?>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="YO"/>
    </div>
  </div>
</form>
