<?php /* Global context icons only */

// Add translation strings
$list = [
    'spinner',
    // Facets
    'collapse-close',
    'collapse-open',
    'facet-checked',
    'facet-exclude',
    'facet-unchecked',
    // Hierarchy tree
    'format-file',
    'format-folder',
    // My Account AJAX
    'my-account',
    'notification',
    'status_pending',
    'status_ready',
    'warning',
    // Record statuses
    'hold',
    'ill-request',
    'storage-retrieval',
];

// To save redundancy:       zip list together
// ala 'icon' => 'icon'
$this->jsIcons()->addStrings(array_combine($list, $list));

echo $this->jsIcons()->getJSON();
