<?php /* Global context icons only */

// Set up icons
$list = [
    'spinner',
    // Channels
    'ui-dots-menu',
    // Facets
    'collapse',
    'collapse-close',
    'collapse-open',
    'facet-checked',
    'facet-exclude',
    'facet-unchecked',
    // Hierarchy tree
    'format-file',
    'format-folder',
    // My Account AJAX
    'my-account',
    'my-account-notification',
    'my-account-warning',
    'status-pending',
    'status-ready',
    // Record statuses
    'check',
    'place-hold',
    'place-ill-request',
    'place-storage-retrieval',
    'status-indicator',
];

// To save redundancy: zip list together
// ala 'icon' => 'icon'
$this->jsIcons()->addStrings(array_combine($list, $list));

echo $this->jsIcons()->getJSON();
