<?php
/**
 * Font Awesome icon set by FortAwesome
 *
 * Website: https://fontawesome.com/
 * Repository: https://github.com/FortAwesome/Font-Awesome
 * Licenses: SIL OFL 1.1 License (Fonts), CC BY 4.0 License (Icons), MIT License (Code)
 */
return [
    'css' => [
        // 'v4-shims.min.css', // activate to add v4 class compatibility
        // 'svg-with-js.min.css', // activate to replace all icons with SVG
    ],
    'js' => [
        // 'all.min.js', // activate to replace all icons with SVG
        // 'v4-shims.min.js', // activate to convert v4 classes to SVG as well
    ],
    'icons' => [
        'sets' => [
            'FontAwesome5' => [
                'template' => 'font',
                'src' => 'all.min.css', // edited to move webfonts folder inside css/
            ],
        ],
        'aliases' => [
            // UI
            'arrow-right' => 'FontAwesome5:fas fa-arrow-right',
            'barcode' => 'FontAwesome5:fas fa-barcode',
            'bookmark' => 'FontAwesome5:far fa-bookmark',
            'cancel' => 'FontAwesome5:fas fa-fan',
            'cart' => 'FontAwesome5:fas fa-briefcase',
            'cart-add' => 'FontAwesome5:far fa-plus-square',
            'cart-empty' => 'FontAwesome5:fas fa-eraser',
            'cart-remove' => 'FontAwesome5:far fa-window-close',
            'check' => 'FontAwesome5:fas fa-check',
            'checked-out' => 'FontAwesome5:fas fa-book',
            'cite' => 'FontAwesome5:fas fa-asterisk',
            'collapse-close' => 'FontAwesome5:fas fa-angle-up',
            'collapse-open' => 'FontAwesome5:fas fa-angle-down',
            'cover-replacement' => 'FontAwesome5:fas fa-photo-video',
            'delete' => 'FontAwesome5:far fa-trash-alt',
            'dropdown-caret' => 'FontAwesome5:fas fa-caret-down',
            'edit' => 'FontAwesome5:fas fa-edit',
            'email' => 'FontAwesome5:fas fa-envelope',
            'export' => 'FontAwesome5:fas fa-share-square',
            'external-link' => 'FontAwesome5:fas fa-external-link-alt',
            'facet-checked' => 'FontAwesome5:fas fa-check-square',
            'facet-exclude' => 'FontAwesome5:far fa-times-circle',
            'facet-unchecked' => 'FontAwesome5:far fa-square',
            'favorites' => 'FontAwesome5:fas fa-star',
            'feedback' => 'FontAwesome5:fas fa-comment-dots',
            'hold' => 'FontAwesome5:fas fa-flag',
            'ill-request' => 'FontAwesome5:fas fa-exchange-alt',
            'loan-history' => 'FontAwesome5:fas fa-history',
            'menu-bars' => 'FontAwesome5:fas fa-bars',
            'more' => 'FontAwesome5:fas fa-angle-right',
            'my-account' => 'FontAwesome5:fas fa-user',
            'notification' => 'FontAwesome5:fas fa-bell',
            'options' => 'FontAwesome5:fas fa-sliders-h',
            'overdrive' => 'FontAwesome5:fas fa-cloud',
            'page-first' => 'FontAwesome5:fas fa-chevron-left-circle',
            'page-last' => 'FontAwesome5:fas fa-chevron-right-circle',
            'page-next' => 'FontAwesome5:fas fa-arrow-right',
            'page-prev' => 'FontAwesome5:fas fa-arrow-left',
            'print' => 'FontAwesome5:fas fa-print',
            'profile' => 'FontAwesome5:far fa-id-card',
            'qrcode' => 'FontAwesome5:fas fa-qrcode',
            'recall' => 'FontAwesome5:fas fa-flag',
            'remove' => 'FontAwesome5:fas fa-close',
            'return' => 'FontAwesome5:fas fa-arrow-right',
            'rss' => 'FontAwesome5:fas fa-rss',
            'save' => 'FontAwesome5:fas fa-save',
            'search' => 'FontAwesome5:fas fa-search',
            'sign-in' => 'FontAwesome5:fas fa-sign-in-alt',
            'sign-out' => 'FontAwesome5:fas fa-sign-out-alt',
            'sms' => 'FontAwesome5:fas fa-sms',
            'spinner' => 'FontAwesome5:fas fa-spinner icon--spin',
            'status_pending' => 'FontAwesome5:fas fa-hourglass-half',
            'status_ready' => 'FontAwesome5:fas fa-bell',
            'storage-retrieval' => 'FontAwesome5:fas fa-truck',
            'tree-context' => 'FontAwesome5:fas fa-sitemap',
            'ui-add' => 'FontAwesome5:fas fa-plus',
            'ui-close' => 'FontAwesome5:fas fa-times',
            'user-list' => 'FontAwesome5:fas fa-star',
            'view-grid' => 'FontAwesome5:fas fa-border-all',
            'view-list' => 'FontAwesome5:fas fa-justify',
            'warning' => 'FontAwesome5:fas fa-exclamation-triangle',
            // Formats (Similar items)
            'format-atlas' => 'FontAwesome5:fas fa-atlas',
            'format-book' => 'FontAwesome5:fas fa-book',
            'format-braille' => 'FontAwesome5:fas fa-braille',
            'format-cdrom' => 'FontAwesome5:fas fa-compact-disc',
            'format-chart' => 'FontAwesome5:fas fa-chart-bar',
            'format-chipcartridge' => 'FontAwesome5:fas fa-microchip',
            'format-collage' => 'FontAwesome5:fas fa-icons',
            'format-default' => 'FontAwesome5:fas fa-book',
            'format-disccartridge' => 'FontAwesome5:fas fa-compact-disc',
            'format-drawing' => 'FontAwesome5:fas fa-drawing-compass',
            'format-ebook' => 'FontAwesome5:fas fa-book-reader',
            'format-electronic' => 'FontAwesome5:fas fa-file-archive',
            'format-file' => 'FontAwesome5:fas fa-file',
            'format-filmstrip' => 'FontAwesome5:fas fa-film',
            'format-flashcard' => 'FontAwesome5:fas fa-swatchbook',
            'format-floppydisk' => 'FontAwesome5:far fa-save',
            'format-folder' => 'FontAwesome5:far fa-folder-open',
            'format-globe' => 'FontAwesome5:fas fa-europe',
            'format-journal' => 'FontAwesome5:fas fa-newspaper',
            'format-kit' => 'FontAwesome5:fas fa-toolbox',
            'format-manuscript' => 'FontAwesome5:fas fa-feather-alt',
            'format-map' => 'FontAwesome5:far fa-map',
            'format-microfilm' => 'FontAwesome5:fas fa-tape',
            'format-motionpicture' => 'FontAwesome5:fas fa-video',
            'format-musicalscore' => 'FontAwesome5:fas fa-music',
            'format-musicrecording' => 'FontAwesome5:fas fa-headphones-alt',
            'format-newspaper' => 'FontAwesome5:fas fa-newspaper',
            'format-online' => 'FontAwesome5:fas fa-link',
            'format-painting' => 'FontAwesome5:fas fa-paint-brush',
            'format-photo' => 'FontAwesome5:far fa-image',
            'format-photonegative' => 'FontAwesome5:fas fa-camera',
            'format-physicalobject' => 'FontAwesome5:fas fa-box-open',
            'format-print' => 'FontAwesome5:fas fa-image',
            'format-sensorimage' => 'FontAwesome5:fas fa-camera',
            'format-serial' => 'FontAwesome5:fas fa-newspaper',
            'format-slide' => 'FontAwesome5:fas fa-film',
            'format-software' => 'FontAwesome5:fas fa-compact-disc',
            'format-soundcassette' => 'FontAwesome5:fas fa-headphones-alt',
            'format-sounddisc' => 'FontAwesome5:fas fa-compact-disc',
            'format-soundrecording' => 'FontAwesome5:fas fa-microphone',
            'format-tapecartridge' => 'FontAwesome5:fas fa-headphones-alt',
            'format-tapecassette' => 'FontAwesome5:fas fa-headphones-alt',
            'format-tapereel' => 'FontAwesome5:fas fa-tape',
            'format-transparency' => 'FontAwesome5:fas fa-chalkboard',
            'format-unknown' => 'FontAwesome5:far fa-file',
            'format-video' => 'FontAwesome5:fas fa-video',
            'format-videocartridge' => 'FontAwesome5:fas fa-video',
            'format-videocassette' => 'FontAwesome5:fas fa-video',
            'format-videodisc' => 'FontAwesome5:fas fa-compact-disc',
            'format-videoreel' => 'FontAwesome5:fas fa-tape',
            // Currencies
            'eur' => 'FontAwesome5:fas fa-euro-sign',
            'gbp' => 'FontAwesome5:fas fa-pound-sign',
            'inr' => 'FontAwesome5:fas fa-rupee-sign',
            'jpy' => 'FontAwesome5:fas fa-yen-sign',
            'krw' => 'FontAwesome5:fas fa-won-sign',
            'rmb' => 'FontAwesome5:fas fa-yen-sign',
            'rub' => 'FontAwesome5:fas fa-ruble-sign',
            'try' => 'FontAwesome5:fas fa-lira-sign',
            'usd' => 'FontAwesome5:fas fa-dollar-sign',
            'won' => 'FontAwesome5:fas fa-won-sign',
            'yen' => 'FontAwesome5:fas fa-yen-sign',
        ],
    ],
];
