<?php
return [
    'css' => [
        // 'v4-shims.min.css', // activate to add v4 class compatibility
        // 'svg-with-js.min.css', // activate to replace all icons with SVG
    ],
    'js' => [
        // 'all.min.js', // activate to replace all icons with SVG
        // 'v4-shims.min.js', // activate to convert v4 classes to SVG as well
    ],
    'icons' => [
        'sets' => [
            'FontAwesome5' => [
                'template' => 'font',
                'src' => 'all.min.css', // edited to move webfonts folder inside css/
            ],
        ],
        'aliases' => [
            // UI
            'arrow-right' => 'FontAwesome5:fas fa-arrow-right',
            'barcode' => 'FontAwesome5:fas fa-barcode',
            'bookmark' => 'FontAwesome5:far fa-bookmark',
            'cancel' => 'FontAwesome5:fas fa-fan',
            'cart' => 'FontAwesome5:fas fa-briefcase',
            'cart-add' => 'FontAwesome5:far fa-plus-square',
            'cart-empty' => 'FontAwesome5:fas fa-eraser',
            'cart-remove' => 'FontAwesome5:far fa-window-close',
            'check' => 'FontAwesome5:fas fa-check',
            'checked-out' => 'FontAwesome5:fas fa-book',
            'cite' => 'FontAwesome5:fas fa-asterisk',
            'collapse-close' => 'FontAwesome5:fas fa-angle-up',
            'collapse-open' => 'FontAwesome5:fas fa-angle-down',
            'cover-replacement' => 'FontAwesome5:fas fa-photo-video',
            'delete' => 'FontAwesome5:far fa-trash-alt',
            'dropdown-caret' => 'FontAwesome5:fas fa-caret-down',
            'edit' => 'FontAwesome5:fas fa-edit',
            'email' => 'FontAwesome5:fas fa-envelope',
            'export' => 'FontAwesome5:fas fa-share-square',
            'external-link' => 'FontAwesome5:fas fa-external-link-alt',
            'facet-checked' => 'FontAwesome5:fas fa-check-square',
            'facet-exclude' => 'FontAwesome5:far fa-times-circle',
            'facet-unchecked' => 'FontAwesome5:far fa-square',
            'favorites' => 'FontAwesome5:fas fa-star',
            'feedback' => 'FontAwesome5:fas fa-comment-dots',
            'hold' => 'FontAwesome5:fas fa-flag',
            'ill-request' => 'FontAwesome5:fas fa-exchange-alt',
            'loan-history' => 'FontAwesome5:fas fa-history',
            'menu-bars' => 'FontAwesome5:fas fa-bars',
            'more' => 'FontAwesome5:fas fa-angle-right',
            'my-account' => 'FontAwesome5:fas fa-user',
            'options' => 'FontAwesome5:fas fa-sliders-h',
            'overdrive' => 'FontAwesome5:fas fa-cloud',
            'page-first' => 'FontAwesome5:fas fa-chevron-left-circle',
            'page-last' => 'FontAwesome5:fas fa-chevron-right-circle',
            'page-next' => 'FontAwesome5:fas fa-arrow-right',
            'page-prev' => 'FontAwesome5:fas fa-arrow-left',
            'print' => 'FontAwesome5:fas fa-print',
            'profile' => 'FontAwesome5:far fa-id-card',
            'qrcode' => 'FontAwesome5:fas fa-qrcode',
            'recall' => 'FontAwesome5:fas fa-flag',
            'remove' => 'FontAwesome5:fas fa-close',
            'return' => 'FontAwesome5:fas fa-arrow-right',
            'rss' => 'FontAwesome5:fas fa-rss',
            'save' => 'FontAwesome5:fas fa-save',
            'search' => 'FontAwesome5:fas fa-search',
            'sign-in' => 'FontAwesome5:fas fa-sign-in-alt',
            'sign-out' => 'FontAwesome5:fas fa-sign-out-alt',
            'sms' => 'FontAwesome5:fas fa-sms',
            'spinner' => 'FontAwesome5:fas fa-spinner icon--spin',
            'storage-retrieval' => 'FontAwesome5:fas fa-truck',
            'tree-context' => 'FontAwesome5:fas fa-sitemap',
            'ui-add' => 'FontAwesome5:fas fa-plus',
            'user-list' => 'FontAwesome5:fas fa-star',
            'view-grid' => 'FontAwesome5:fas fa-border-all',
            'view-list' => 'FontAwesome5:fas fa-justify',
            'warning' => 'FontAwesome5:fas fa-exclamation-triangle',
            // Formats (Similar items)
            // 'format-atlas' => 'FontAwesome5:fas fa-map-2',
            // 'format-book' => 'FontAwesome5:fas fa-book',
            // 'format-braille' => 'FontAwesome5:fas fa-fingerprint',
            // 'format-cdrom' => 'FontAwesome5:fas fa-dvd',
            // 'format-chart' => 'FontAwesome5:fas fa-chart-box',
            // 'format-chipcartridge' => 'FontAwesome5:fas fa-macbook',
            // 'format-collage' => 'FontAwesome5:fas fa-layout-masonry',
            // 'format-default' => 'FontAwesome5:fas fa-book',
            // 'format-disccartridge' => 'FontAwesome5:fas fa-dvd',
            // 'format-drawing' => 'FontAwesome5:fas fa-image-edit',
            // 'format-ebook' => 'FontAwesome5:fas fa-book-read',
            // 'format-electronic' => 'FontAwesome5:fas fa-file-zip',
            // 'format-filmstrip' => 'FontAwesome5:fas fa-film',
            // 'format-flashcard' => 'FontAwesome5:fas fa-pantone',
            // 'format-floppydisk' => 'FontAwesome5:fas fa-save-2',
            // 'format-globe' => 'FontAwesome5:fas fa-globe',
            // 'format-journal' => 'FontAwesome5:fas fa-article',
            // 'format-kit' => 'FontAwesome5:fas fa-briefcase-4',
            // 'format-manuscript' => 'FontAwesome5:fas fa-pen-nib',
            // 'format-map' => 'FontAwesome5:fas fa-treasure-map',
            // 'format-microfilm' => 'FontAwesome5:fas fa-movie-2',
            // 'format-motionpicture' => 'FontAwesome5:fas fa-movie',
            // 'format-musicalscore' => 'FontAwesome5:fas fa-file-music',
            // 'format-musicrecording' => 'FontAwesome5:fas fa-headphone',
            // 'format-newspaper' => 'FontAwesome5:fas fa-newspaper',
            // 'format-online' => 'FontAwesome5:fas fa-file-cloud',
            // 'format-painting' => 'FontAwesome5:fas fa-paint',
            // 'format-photo' => 'FontAwesome5:fas fa-image',
            // 'format-photonegative' => 'FontAwesome5:fas fa-camera',
            // 'format-physicalobject' => 'FontAwesome5:fas fa-archive',
            // 'format-print' => 'FontAwesome5:fas fa-image-2-fill',
            // 'format-sensorimage' => 'FontAwesome5:fas fa-camera-lens',
            // 'format-serial' => 'FontAwesome5:fas fa-file-list-3',
            // 'format-slide' => 'FontAwesome5:fas fa-slideshow',
            // 'format-software' => 'FontAwesome5:fas fa-dvd',
            // 'format-soundcassette' => 'FontAwesome5:fas fa-tape',
            // 'format-sounddisc' => 'FontAwesome5:fas fa-album',
            // 'format-soundrecording' => 'FontAwesome5:fas fa-headphones',
            // 'format-tapecartridge' => 'FontAwesome5:fas fa-tape',
            // 'format-tapecassette' => 'FontAwesome5:fas fa-tape',
            // 'format-tapereel' => 'FontAwesome5:fas fa-record-mail',
            // 'format-transparency' => 'FontAwesome5:fas fa-file',
            // 'format-unknown' => 'FontAwesome5:fas fa-file-unknow',
            // 'format-video' => 'FontAwesome5:fas fa-movie',
            // 'format-videocartridge' => 'FontAwesome5:fas fa-film',
            // 'format-videocassette' => 'FontAwesome5:fas fa-vidicon',
            // 'format-videodisc' => 'FontAwesome5:fas fa-dvd',
            // 'format-videoreel' => 'FontAwesome5:fas fa-movie-2',
            // Currencies
            // 'eur' => 'FontAwesome5:fas fa-money-euro-circle',
            // 'gbp' => 'FontAwesome5:fas fa-money-pound-circle',
            // 'jpy' => 'FontAwesome5:fas fa-money-yen-circle',
            // 'usd' => 'FontAwesome5:fas fa-money-dollar-circle',
            // 'yen' => 'FontAwesome5:fas fa-money-yen-circle',
        ],
    ],
];
