<?php
return [
    'extends' => 'bootstrap3',
    'icons' => [
        'defaultSet' => 'Fugue',
        'sets' => [
            /**
             * Define icon sets here.
             *
             * All sets need:
             * - 'template': which template the icon renders with
             * - 'src': the location of the relevant resource (font, css, images)
             * - 'prefix': prefix to place before each icon name for convenience
             *             (ie. fa fa- for FontAwesome, default "")
             */
            'Fugue' => [
                'template' => 'images',
                'src' => 'icons', // Processed via imageLink
            ],
        ],
        'aliases' => [
            // UI
            'arrow-right' => 'arrow_right.png',
            // 'barcode' => 'FontAwesome:barcode',
            'bookmark' => 'bookmark_add.png',
            'cancel' => 'cancel.png',
            'cart' => 'bookbag.png',
            'cart-add' => 'bookbag_add.png',
            'cart-empty' => 'bookbag_empty.png',
            'cart-remove' => 'bookbag_delete.png',
            // 'check' => 'FontAwesome:check',
            'checked-out' => 'book.png',
            'cite' => 'asterisk_orange.png',
            'collapse-close' => 'bullet_arrow_up.png',
            'collapse-open' => 'bullet_arrow_down.png',
            'cover-replacement' => 'images.png',
            'delete' => 'bin.png',
            // 'dropdown-caret' => 'FontAwesome:caret-down',
            'edit' => 'edit.png',
            'email' => 'email.png',
            'export' => 'link_go.png',
            'external-link' => 'link_go.png',
            // 'facet-checked' => 'FontAwesome:times',
            // 'facet-exclude' => 'FontAwesome:square-o',
            // 'facet-unchecked' => 'FontAwesome:square-o',
            'favorites' => 'star.png',
            'feedback' => 'email.png',
            'hold' => 'flag_blue.png',
            'ill-request' => 'arrow_switch.png',
            'loan-history' => 'clock.png',
            // 'menu-bars' => 'FontAwesome:bars',
            'more' => 'arrow_right.png',
            'my-account' => 'user.png',
            'options' => 'cog.png',
            'overdrive' => 'drive_web.png',
            'page-first' => 'resultset_first.png',
            'page-last' => 'resultset_last.png',
            'page-next' => 'resultset_next.png',
            'page-prev' => 'resultset_prev.png',
            'print' => 'printer.png',
            'profile' => 'user.png',
            'qrcode' => 'qrcode.png',
            'recall' => 'flag_blue.png',
            'remove' => 'cross.png',
            'return' => 'arrow_right.png',
            'rss' => 'rss.png',
            'save' => 'disk.png',
            'search' => 'magnifier.png',
            'sign-in' => 'door_in.png',
            'sign-out' => 'door_out.png',
            'sms' => 'phone.png',
            // 'spinner' => 'FontAwesome:spinner fa-spin',
            'storage-retrieval' => 'lorry.png',
            'tree-context' => 'treeCurrent.png',
            'ui-add' => 'add.png',
            'user-list' => 'star.png',
            'view-grid' => 'view_grid.png',
            'view-list' => 'view_list.png',
            'warning' => 'error.png',
            // Formats (Similar items)
            'format-atlas' => 'map.png',
            'format-book' => 'book.png',
            'format-braille' => 'book.png',
            'format-cdrom' => 'cd.png',
            'format-chart' => 'chart_bar.png',
            'format-chipcartridge' => 'computer.png',
            'format-collage' => 'photos.png',
            'format-default' => 'book.png',
            'format-disccartridge' => 'computer.png',
            'format-drawing' => 'edit.png',
            'format-ebook' => 'book_link.png',
            'format-electronic' => 'page_white_zip.png',
            'format-filmstrip' => 'film.png',
            'format-flashcard' => 'lightning.png',
            'format-floppydisk' => 'disk.png',
            'format-globe' => 'world.png',
            'format-journal' => 'page.png',
            'format-kit' => 'box.png',
            'format-manuscript' => 'file_white_text.png',
            'format-map' => 'map.png',
            'format-microfilm' => 'film.png',
            'format-motionpicture' => 'page_white_camera.png',
            'format-musicalscore' => 'music.png',
            'format-musicrecording' => 'music.png',
            'format-newspaper' => 'newspaper.png',
            'format-online' => 'book_link.png',
            'format-painting' => 'page_white_paint.png',
            'format-photo' => 'photo.png',
            'format-photonegative' => 'photos.png',
            'format-physicalobject' => 'bricks.png',
            'format-print' => 'photo.png',
            'format-sensorimage' => 'camera.png',
            'format-serial' => 'layers.png',
            'format-slide' => 'shape_move_forward.png',
            'format-software' => 'page_white_cd.png',
            'format-soundcassette' => 'sound.png',
            'format-sounddisc' => 'cd.png',
            'format-soundrecording' => 'sound.png',
            'format-tapecartridge' => 'sound.png',
            'format-tapecassette' => 'music.png',
            'format-tapereel' => 'film.png',
            'format-transparency' => 'shape_move_forward.png',
            'format-unknown' => 'page_red.png',
            'format-video' => 'film.png',
            'format-videocartridge' => 'film.png',
            'format-videocassette' => 'film.png',
            'format-videodisc' => 'cd.png',
            'format-videoreel' => 'film.png',
            // Currencies
            'eur' => 'money_euro.png',
            'gbp' => 'money_pound.png',
            // 'inr' => 'FontAwesome:inr',
            'jpy' => 'money_yen.png',
            // 'krw' => 'FontAwesome:krw',
            // 'rmb' => 'FontAwesome:rmb',
            // 'rub' => 'FontAwesome:rub',
            // 'try' => 'FontAwesome:try',
            'usd' => 'money_dollar.png',
            // 'won' => 'FontAwesome:won',
            'yen' => 'money_yen.png',
        ]
    ]
];
